In [1]:
import pandas as pd
import json
import subprocess
import os

In [2]:
stats = pd.read_csv("../data/disease_model_stats.csv")

## 0004992 - Generic Cancer

In [3]:
subprocess.run([
    "python", "../src/predict.py",
    "-input", "../demo/metadata_mouse_title_processed.tsv",
    "-id", "../demo/metadata_mouse_ID.tsv",
    "-input_embed", "../demo/metadata_mouse_title_embedding.npz",
    "-train_embed", "../data/disease_desc_embedding.npz",
    "-model", "../bins/MONDO_0004992__model.pkl",
    "-out", "../results/"
])

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.87 s to load data
predicting labels
took 10.31 s to predict
retrieving predictive words
took 0.45 s to retrieve predictive words
saving output
took 0.19 min to load, predict, retrieve predictive words and save MONDO_0004992 for 4066 instances

CompletedProcess(args=['python', '../src/predict.py', '-input', '../demo/metadata_mouse_title_processed.tsv', '-id', '../demo/metadata_mouse_ID.tsv', '-input_embed', '../demo/metadata_mouse_title_embedding.npz', '-train_embed', '../data/disease_desc_embedding.npz', '-model', '../bins/MONDO_0004992__model.pkl', '-out', '../results/'], returncode=0)

In [4]:
preds_0004992 = pd.read_csv("../results/MONDO_0004992__preds.csv")
preds_0004992[preds_0004992['log2(prob/prior)'] > 0]

,ID,prob,log2(prob/prior),related_words
0,GSE87388,0.961283,0.487215,"cancer,pancreatic,tumor"
1,GSE81941,0.958960,0.483724,"breast,cancer,cell"
2,GSE74490,0.953467,0.475437,"cancer,pancreatic"
3,GSE59831,0.949153,0.468895,"analysis,cancer,cells,epithelial,lung,rnaseq,t..."
4,GSE77623,0.946461,0.464798,"cancer,expression,prostate,tumor"
...,...,...,...,...
90,GSE97489,0.692138,0.013315,"sarcoma,soft,tissues"
91,GSE66068,0.692047,0.013125,"acute,inhibition,leukemia,myeloid,rnaseq"
92,GSE67790,0.690774,0.010469,"cancer,colon,liver"
93,GSE74650,0.689315,0.007417,"acute,cells,inhibition,leukemia,myeloid,rnaseq..."
94,GSE80745,0.686404,0.001312,"acute,analysis,cells,expression,leukemia,myelo..."

## Overview of cancer children & if there is model

In [16]:
with open("../data/cancer_children.json") as f:
    children = json.load(f)

In [19]:
terms = children['_embedded']['terms']
ids = [t['short_form'] for t in terms]
names = [t['label'] for t in terms]
models = []
for id in ids:
    match = stats['ID'].str.replace(":", "_").str.contains(id).any()
    models.append(match)

In [25]:
cancer_children_1 = {'ids': ids, 'names': names, 'models': models}
cancer_children_1 = pd.DataFrame(cancer_children_1)
cancer_children_1

              ids                              names  models
0   MONDO_0858997     cancer of unknown primary site   False
1   MONDO_0850125                  malignant adenoma   False
2   MONDO_0036501      refractory malignant neoplasm   False
3   MONDO_0024881       secondary malignant neoplasm    True
4   MONDO_0024637     malignant soft tissue neoplasm    True
5   MONDO_0021069       malignant endocrine neoplasm    True
6   MONDO_0020665      high grade malignant neoplasm    True
7   MONDO_0020663    malignant spindle cell neoplasm    True
8   MONDO_0020633                  anaplastic cancer    True
9   MONDO_0006295  malignant urinary system neoplasm    True
10  MONDO_0006292             malignant mesothelioma    True
11  MONDO_0006290          malignant germ cell tumor    True
12  MONDO_0006517       childhood malignant neoplasm    True
13  MONDO_0005872              nervous system cancer    True
14  MONDO_0005853           malignant mixed neoplasm    True
15  MONDO_0005941             retroperitoneal cancer    True
16  MONDO_0005627               head and neck cancer    True
17  MONDO_0005565                           blastoma   False
18  MONDO_0005089                            sarcoma    True
19  MONDO_0004993                          carcinoma    True
20  MONDO_0003633             malignant mesenchymoma   False
21  MONDO_0003340             malignant glomus tumor   False
22  MONDO_0003274                    thoracic cancer    True
23  MONDO_0002813                  lipomatous cancer    True
24  MONDO_0002516            digestive system cancer    True
25  MONDO_0002402         malignant giant cell tumor   False
26  MONDO_0002149         reproductive system cancer    True
27  MONDO_0002100              cardiovascular cancer    True
28  MONDO_0002087                  peritoneum cancer   False
29  MONDO_0000653        integumentary system cancer    True
30  MONDO_0000376          respiratory system cancer    True
31  MONDO_0000637      musculoskeletal system cancer    True
32  MONDO_0000621               immune system cancer    True

## Running mouse data on cancer & Pick out the children cancer with largest number of predictions ($log(prob) > 1$)

In [32]:
# # Preprocess
# subprocess.run([
#     "python", "../src/preprocess.py",
#     "-input", "../demo/metadata_mouse_title.tsv",
#     "-out", "../demo/metadata_mouse_title_processed.tsv"
# ])

# # Generate embeddings
# subprocess.run([
#     "python", "../src/embedding_lookup_table.py",
#     "-input", "../demo/metadata_mouse_title_processed.tsv",
#     "-out", "../demo/metadata_mouse_title_embedding.npz"
# ])

# Predict
for index, row in cancer_children_1.iterrows():
    if row['models']:
        subprocess.run([
            "python", "../src/predict.py",
            "-input", "../demo/metadata_mouse_title_processed.tsv",
            "-id", "../demo/metadata_mouse_ID.tsv",
            "-input_embed", "../demo/metadata_mouse_title_embedding.npz",
            "-train_embed", "../data/disease_desc_embedding.npz",
            "-model", f"../bins/{row['ids']}__model.pkl",
            "-out", "../results/cancer_children_mouse/"
        ])

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.91 s to load data
predicting labels
took 9.63 s to predict
retrieving predictive words
took 0.18 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0024881 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.88 s to load data
predicting labels
took 9.47 s to predict
retrieving predictive words
took 0.18 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0024637 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.88 s to load data
predicting labels
took 9.62 s to predict
retrieving predictive words
took 0.25 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0021069 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.88 s to load data
predicting labels
took 9.45 s to predict
retrieving predictive words
took 0.24 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0020665 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.87 s to load data
predicting labels
took 9.65 s to predict
retrieving predictive words
took 0.16 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0020663 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.86 s to load data
predicting labels
took 9.53 s to predict
retrieving predictive words
took 0.16 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0020633 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.34 s to predict
retrieving predictive words
took 0.21 s to retrieve predictive words
saving output
took 0.17 min to load, predict, retrieve predictive words and save MONDO_0006295 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.42 s to predict
retrieving predictive words
took 0.16 s to retrieve predictive words
saving output
took 0.17 min to load, predict, retrieve predictive words and save MONDO_0006292 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.87 s to load data
predicting labels
took 9.42 s to predict
retrieving predictive words
took 0.16 s to retrieve predictive words
saving output
took 0.17 min to load, predict, retrieve predictive words and save MONDO_0006290 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.50 s to predict
retrieving predictive words
took 0.20 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0006517 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.87 s to load data
predicting labels
took 9.45 s to predict
retrieving predictive words
took 0.29 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0005872 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.86 s to load data
predicting labels
took 9.55 s to predict
retrieving predictive words
took 0.17 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0005853 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.47 s to predict
retrieving predictive words
took 0.16 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0005941 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.87 s to load data
predicting labels
took 9.62 s to predict
retrieving predictive words
took 0.21 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0005627 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.49 s to predict
retrieving predictive words
took 0.19 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0005089 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.53 s to predict
retrieving predictive words
took 0.39 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0004993 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.53 s to predict
retrieving predictive words
took 0.27 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0003274 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.87 s to load data
predicting labels
took 9.47 s to predict
retrieving predictive words
took 0.16 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0002813 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.87 s to load data
predicting labels
took 9.29 s to predict
retrieving predictive words
took 0.35 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0002516 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.86 s to load data
predicting labels
took 9.50 s to predict
retrieving predictive words
took 0.21 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0002149 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.87 s to load data
predicting labels
took 9.47 s to predict
retrieving predictive words
took 0.16 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0002100 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.31 s to predict
retrieving predictive words
took 0.18 s to retrieve predictive words
saving output
took 0.17 min to load, predict, retrieve predictive words and save MONDO_0000653 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.52 s to predict
retrieving predictive words
took 0.22 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0000376 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.88 s to load data
predicting labels
took 9.57 s to predict
retrieving predictive words
took 0.28 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0000637 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.46 s to predict
retrieving predictive words
took 0.34 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0000621 for 4066 instances

In [35]:
files = [f for f in os.listdir("../results/cancer_children_mouse") if f.endswith(".csv")]

dfs = []
for f in files:
    df = pd.read_csv(os.path.join("../results/cancer_children_mouse", f))
    df['source'] = f.replace("__preds.csv", "")
    dfs.append(df)

all_preds = pd.concat(dfs, ignore_index=True)
all_preds.to_csv(
    os.path.join("../results/cancer_children_mouse", "all_cancer_predictions.csv"),
    index=False
)
print("Saved all_cancer_predictions.csv")

Saved all_cancer_predictions.csv

In [41]:
all_preds[all_preds['log2(prob/prior)']>0].groupby('source').size().reset_index(name='count').sort_values('count', ascending=False)

           source  count
1   MONDO_0000621    346
2   MONDO_0000637    259
21  MONDO_0020665    231
6   MONDO_0002516    230
24  MONDO_0024881    221
13  MONDO_0005872    208
9   MONDO_0004993    187
22  MONDO_0021069    151
23  MONDO_0024637    136
12  MONDO_0005853    135
17  MONDO_0006295    119
18  MONDO_0006517    102
8   MONDO_0003274     90
11  MONDO_0005627     81
0   MONDO_0000376     74
5   MONDO_0002149     74
3   MONDO_0000653     57
15  MONDO_0006290     30
19  MONDO_0020633     23
10  MONDO_0005089     22
14  MONDO_0005941     18
7   MONDO_0002813     11
4   MONDO_0002100      2
20  MONDO_0020663      2
16  MONDO_0006292      1

## Choose 0000621 - immune system cancer & check children nodes distribution

In [48]:
# ! wget https://www.ebi.ac.uk/ols4/api/ontologies/mondo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0000621/children

In [49]:
with open("../data/0000621_children.json") as f:
    children = json.load(f)

terms = children['_embedded']['terms']
ids = [t['short_form'] for t in terms]
names = [t['label'] for t in terms]
models = []
for id in ids:
    match = stats['ID'].str.replace(":", "_").str.contains(id).any()
    models.append(match)

cancer_children_2 = pd.DataFrame({'ids': ids, 'names': names, 'models': models})
cancer_children_2

              ids                                              names  models
0   MONDO_0021138                                 bone marrow cancer    True
1   MONDO_0019475     subcutaneous panniculitis-like T-cell lymphoma   False
2   MONDO_0019024                                  mast cell sarcoma   False
3   MONDO_0018223  systemic Epstein-Barr virus-positive T-cell ly...   False
4   MONDO_0015819         indolent primary cutaneous B-cell lymphoma   False
5   MONDO_0009693                                plasma cell myeloma    True
6   MONDO_0006462        thyroid gland diffuse large B-cell lymphoma   False
7   MONDO_0006418  small intestinal enteropathy-associated T-cell...   False
8   MONDO_0006417     small intestinal diffuse large B-cell lymphoma   False
9   MONDO_0006416                  small intestinal Burkitt lymphoma   False
10  MONDO_0006387    primary pulmonary diffuse large B-cell lymphoma   False
11  MONDO_0006268                liver diffuse large B-cell lymphoma   False
12  MONDO_0006158           colorectal diffuse large B-cell lymphoma   False
13  MONDO_0006225                       gastric mantle cell lymphoma   False
14  MONDO_0006150                             colon Burkitt lymphoma   False
15  MONDO_0006117               breast diffuse large B-cell lymphoma   False
16  MONDO_0004685                             Waldeyer's ring cancer   False
17  MONDO_0004380                             dendritic cell sarcoma   False
18  MONDO_0002756                solitary plasmacytoma of chest wall   False
19  MONDO_0002586                                      thymus cancer   False
20  MONDO_0002571            primary central nervous system lymphoma   False
21  MONDO_0000612                            lymphatic system cancer    True
22  MONDO_0000872      B-cell childhood acute lymphoblastic leukemia    True
23  MONDO_0000871        T-cell childhood acute lymphocytic leukemia    True

In [51]:
# Predict
for index, row in cancer_children_2.iterrows():
    if row['models']:
        subprocess.run([
            "python", "../src/predict.py",
            "-input", "../demo/metadata_mouse_title_processed.tsv",
            "-id", "../demo/metadata_mouse_ID.tsv",
            "-input_embed", "../demo/metadata_mouse_title_embedding.npz",
            "-train_embed", "../data/disease_desc_embedding.npz",
            "-model", f"../bins/{row['ids']}__model.pkl",
            "-out", "../results/0000621_children_mouse/"
        ])

files = [f for f in os.listdir("../results/0000621_children_mouse") if f.endswith(".csv")]

dfs = []
for f in files:
    df = pd.read_csv(os.path.join("../results/0000621_children_mouse", f))
    df['source'] = f.replace("__preds.csv", "")
    dfs.append(df)

all_preds = pd.concat(dfs, ignore_index=True)
all_preds.to_csv(
    os.path.join("../results/0000621_children_mouse", "all_cancer_predictions.csv"),
    index=False
)
print("Saved all_cancer_predictions.csv")

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.89 s to load data
predicting labels
took 9.46 s to predict
retrieving predictive words
took 0.31 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0021138 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.86 s to load data
predicting labels
took 9.41 s to predict
retrieving predictive words
took 0.19 s to retrieve predictive words
saving output
took 0.17 min to load, predict, retrieve predictive words and save MONDO_0009693 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.32 s to predict
retrieving predictive words
took 0.16 s to retrieve predictive words
saving output
took 0.17 min to load, predict, retrieve predictive words and save MONDO_0000612 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.86 s to load data
predicting labels
took 9.38 s to predict
retrieving predictive words
took 0.17 s to retrieve predictive words
saving output
took 0.17 min to load, predict, retrieve predictive words and save MONDO_0000872 for 4066 instances

/home/rfu_smith_edu/.local/lib/python3.13/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loading data
took 0.85 s to load data
predicting labels
took 9.94 s to predict
retrieving predictive words
took 0.16 s to retrieve predictive words
saving output
took 0.18 min to load, predict, retrieve predictive words and save MONDO_0000871 for 4066 instances
Saved all_cancer_predictions.csv

In [52]:
all_preds[all_preds['log2(prob/prior)']>0].groupby('source').size().reset_index(name='count').sort_values('count', ascending=False)

          source  count
4  MONDO_0021138    228
2  MONDO_0000872    116
1  MONDO_0000871     75
3  MONDO_0009693     56
0  MONDO_0000612      9

In [55]:
cancer_children_2[cancer_children_2['models']]

              ids                                          names  models
0   MONDO_0021138                             bone marrow cancer    True
5   MONDO_0009693                            plasma cell myeloma    True
21  MONDO_0000612                        lymphatic system cancer    True
22  MONDO_0000872  B-cell childhood acute lymphoblastic leukemia    True
23  MONDO_0000871    T-cell childhood acute lymphocytic leukemia    True